name: Delete merged branch after pr to master

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Delete merged branch
        uses: SvanBoxel/delete-merged-branch@1.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
