name: Delete merged branch after pr to master

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: calos0921/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
